language: ruby
rvm:
  - 1.8.7
script: "rake spec"
branches:
  only:
    - master
notifications:
  email:
    - lkreczko@gmail.com
gemfile: .gemfile
env:
  - PUPPET_VERSION=2.7.21       # latest 2.7; PE 2.8.0+
  - PUPPET_VERSION=3.2.3       # latest 3.2; 