name 'kreczko-htcondor'
version '0.0.1'

author 'kreczko'
license 'Apache License, Version 2.0'
project_page 'https://github.com/HEP-Puppet'
source 'git@github.com:HEP-Puppet/puppet-htcondor.git'
summary 'Puppet module for HTCondor batch system'
description 'Puppet module for HTCondor batch system'
dependency 'puppetlabs/firewall', '>=0.3.1'
dependency 'puppetlabs/stdlib', '>=4.1.0'
